#!/usr/bin/env python3
"""
Advanced Strands Agent Example
Demonstrates multi-agent patterns and specialized agents working together.
"""

from strands import Agent, tool
from strands_tools import calculator, http_request

# Custom tools for different domains
@tool
def analyze_data(data: str) -> str:
    """Analyze numerical data and provide insights.
    
    Args:
        data: Comma-separated numerical values
    """
    try:
        numbers = [float(x.strip()) for x in data.split(',')]
        avg = sum(numbers) / len(numbers)
        max_val = max(numbers)
        min_val = min(numbers)
        return f"Analysis: Average={avg:.2f}, Max={max_val}, Min={min_val}, Count={len(numbers)}"
    except:
        return "Error: Please provide comma-separated numbers"

@tool
def format_report(title: str, content: str) -> str:
    """Format content into a professional report.
    
    Args:
        title: Report title
        content: Report content
    """
    return f"""
📊 {title.upper()}
{'='*50}

{content}

Generated by Strands Agent System
{'='*50}
"""

def main():
    print("🚀 Creating Specialized Strands Agents...")
    
    # Data Analyst Agent
    data_agent = Agent(
        tools=[calculator, analyze_data],
        system_prompt="You are a data analyst. Focus on numerical analysis and calculations. Be precise and provide clear insights."
    )
    
    # Report Writer Agent  
    report_agent = Agent(
        tools=[format_report],
        system_prompt="You are a professional report writer. Create well-structured, clear reports from provided data."
    )
    
    # Coordinator Agent
    coordinator = Agent(
        tools=[calculator, http_request],
        system_prompt="You are a project coordinator. You delegate tasks to specialists and synthesize results."
    )
    
    print("✅ Three specialized agents created!")
    print("\n" + "="*60)
    print("MULTI-AGENT WORKFLOW DEMONSTRATION")
    print("="*60)
    
    # Simulate a multi-agent workflow
    print("\n1️⃣ Data Agent: Analyzing sales data...")
    sales_data = "120, 150, 98, 200, 175, 145, 190, 165"
    analysis = data_agent(f"Analyze this sales data: {sales_data}")
    print(f"📊 Data Analysis: {analysis}")
    
    print("\n2️⃣ Report Agent: Creating formatted report...")
    report = report_agent(f"Create a report titled 'Weekly Sales Analysis' with this content: {analysis}")
    print(f"📝 Report Generated: {report}")
    
    print("\n3️⃣ Coordinator: Providing executive summary...")
    summary = coordinator(f"Based on this analysis: '{analysis}', provide a brief executive summary with recommendations.")
    print(f"🎯 Executive Summary: {summary}")
    
    print("\n" + "="*60)
    print("CONVERSATION MEMORY TEST")
    print("="*60)
    
    # Test conversation memory across interactions
    coordinator("Remember that our target sales average is 160 per week.")
    performance_check = coordinator("How did we perform against our target based on the previous analysis?")
    print(f"📈 Performance Check: {performance_check}")
    
    print("\n✨ Multi-agent workflow complete!")
    print("🔥 Key Features Demonstrated:")
    print("   • Specialized agents with different tools and prompts")
    print("   • Tool usage for calculations and data analysis") 
    print("   • Conversation memory and context retention")
    print("   • Multi-step workflows with agent coordination")

if __name__ == "__main__":
    main()